name: Lint
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install modules
              run: yarn
            - name: Run ESLint
              run: yarn run eslint --ignore-path .eslintignore --ext .js,.ts .